spring:
  application:
    name: auth
  datasource:
    url: jdbc:mysql://mymysql:3306/board?serverTimezone=Asia/Seoul
    username: ${username}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: create

