spring:
  application:
    name: auth
  datasource:
    url: jdbc:mysql://10.128.0.9:3307/board?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
