spring:
  application:
    name: auth
  datasource:
    url: jdbc:mysql://35.232.141.108:3306/board?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
