spring:
  application:
    name: auth
  datasource:
    url: jdbc:mysql://34.135.17.167:3307/board?serverTimezone=Asia/Seoul
    username: ${username}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: create

